kind: pipeline
name: test

steps:
- name: flake8
  image: alpine/flake8:3.7.7
  commands:
  - flake8

---

kind: pipeline
name: publish to docker hub

trigger:
  status:
  - success
  event:
  - push
  - tag

depends_on:
- test

steps:
- name: docker push branch ${DRONE_COMMIT_BRANCH}
  image: plugins/docker
  settings:
    repo: liquidinvestigations/crji-avere-europarl
    tags: ${DRONE_COMMIT_BRANCH}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push

- name: docker push autotag + latest
  image: plugins/docker
  settings:
    repo: liquidinvestigations/crji-avere-europarl
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

---

kind: pipeline
name: test app

depends_on:
- publish to docker hub

steps:
- name: test
  image: liquidinvestigations/crji-avere-europarl:${DRONE_COMMIT_BRANCH}
  commands:
    - python3 /app/scraper/main.py --id 124831
    - ls /app/scraper/data
    - ls '/app/scraper/data/TEST - 124831'
    - ls '/app/scraper/data/TEST - 124831/Home.html'
---
kind: secret
name: docker_username
get:
  path: liquid/ci/drone.docker
  name: username

---
kind: secret
name: docker_password
get:
  path: liquid/ci/drone.docker
  name: password
